/**
 * Ganesha asset manifest.
 *
 * Prototype-stage assets are procedural (generator ids resolved by the web
 * engine); GLB-stage assets load real mesh files through GLTFLoader.
 * Replacing a procedural prototype with a production sculpt means changing
 * its `source` to a GLB path and bumping `version`; nothing else changes.
 */
import type { AssetDefinition } from "../types";

const proto = { printSourceAvailable: false } as const;

export const GANESHA_ASSETS: readonly AssetDefinition[] = [
  // ---- BODY -------------------------------------------------------------
  {
    id: "ganesha.body.classic",
    version: 2,
    name: "Classic Body",
    description: "Traditional full-bellied lambodara build.",
    kind: { type: "part", slot: "body" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.body", params: { belly: 1 } },
    materialZones: ["skin", "skinSecondary"],
    category: "body",
    printability: proto,
  },
  {
    id: "ganesha.body.slender",
    version: 2,
    name: "Slender Body",
    description: "Slimmer, upright build — Bal Ganesha style.",
    kind: { type: "part", slot: "body" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.body", params: { belly: 0.45 } },
    materialZones: ["skin", "skinSecondary"],
    category: "body",
    printability: proto,
  },
  {
    id: "ganesha.body.mahodara",
    version: 1,
    name: "Mahodara Body",
    description: "The great-bellied form, broad and imposing.",
    kind: { type: "part", slot: "body" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.body", params: { belly: 1.35 } },
    materialZones: ["skin", "skinSecondary"],
    category: "body",
    printability: proto,
  },

  // ---- HEAD -------------------------------------------------------------
  {
    id: "ganesha.head.classic",
    version: 2,
    name: "Classic Head",
    description: "Broad elephant head with twin cranial domes.",
    kind: { type: "part", slot: "head" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.head", params: { dome: 1, cheek: 1 } },
    materialZones: ["skin"],
    category: "head",
    printability: proto,
  },
  {
    id: "ganesha.head.young",
    version: 2,
    name: "Bal Ganesha Head",
    description: "Rounder, youthful head with fuller cheeks.",
    kind: { type: "part", slot: "head" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.head", params: { dome: 0.72, cheek: 1.15 } },
    materialZones: ["skin"],
    category: "head",
    printability: proto,
  },
  {
    id: "ganesha.head.bhala",
    version: 1,
    name: "Bhalachandra Head",
    description: "High-domed forehead variant.",
    kind: { type: "part", slot: "head" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.head", params: { dome: 1.2, cheek: 0.9 } },
    materialZones: ["skin"],
    category: "head",
    printability: proto,
  },

  // ---- EARS -------------------------------------------------------------
  {
    id: "ganesha.ears.large",
    version: 2,
    name: "Large Ears",
    description: "Wide winnowing-fan ears.",
    kind: { type: "part", slot: "ears" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.ears", params: { size: 1, fold: 0 } },
    materialZones: ["skin", "skinSecondary"],
    morphTargets: ["earSize", "earAngle"],
    category: "head",
    printability: proto,
  },
  {
    id: "ganesha.ears.folded",
    version: 2,
    name: "Folded Ears",
    description: "Ears angled back with a soft fold.",
    kind: { type: "part", slot: "ears" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.ears", params: { size: 0.88, fold: 1 } },
    materialZones: ["skin", "skinSecondary"],
    morphTargets: ["earSize", "earAngle"],
    category: "head",
    printability: proto,
  },
  {
    id: "ganesha.ears.small",
    version: 1,
    name: "Small Ears",
    kind: { type: "part", slot: "ears" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.ears", params: { size: 0.72, fold: 0 } },
    materialZones: ["skin", "skinSecondary"],
    morphTargets: ["earSize", "earAngle"],
    category: "head",
    printability: proto,
  },

  // ---- TRUNK ------------------------------------------------------------
  {
    id: "ganesha.trunk.leftCurl",
    version: 2,
    name: "Left-Curled Trunk",
    description: "Vamamukhi — trunk curving to the left, the most common form.",
    kind: { type: "part", slot: "trunk" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.trunk", params: { curl: 1 } },
    materialZones: ["skin"],
    morphTargets: ["trunkLength", "trunkCurl"],
    category: "face",
    printability: proto,
  },
  {
    id: "ganesha.trunk.rightCurl",
    version: 2,
    name: "Right-Curled Trunk",
    description: "Dakshinabhimukhi — trunk curving to the right.",
    kind: { type: "part", slot: "trunk" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.trunk", params: { curl: -1 } },
    materialZones: ["skin"],
    morphTargets: ["trunkLength", "trunkCurl"],
    category: "face",
    printability: proto,
  },
  {
    id: "ganesha.trunk.straight",
    version: 1,
    name: "Straight Trunk",
    description: "Trunk hanging centered with a gentle forward curl.",
    kind: { type: "part", slot: "trunk" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.trunk", params: { curl: 0 } },
    materialZones: ["skin"],
    morphTargets: ["trunkLength", "trunkCurl"],
    category: "face",
    printability: proto,
  },

  // ---- TUSKS ------------------------------------------------------------
  {
    id: "ganesha.tusks.single",
    version: 2,
    name: "Ekadanta",
    description: "One whole tusk, one broken — the classic Ekadanta form.",
    kind: { type: "part", slot: "tusks" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.tusks", params: { broken: 1, scale: 1 } },
    materialZones: [],
    category: "face",
    printability: proto,
  },
  {
    id: "ganesha.tusks.double",
    version: 2,
    name: "Double Tusks",
    kind: { type: "part", slot: "tusks" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.tusks", params: { broken: 0, scale: 1 } },
    materialZones: [],
    category: "face",
    printability: proto,
  },
  {
    id: "ganesha.tusks.short",
    version: 1,
    name: "Short Tusks",
    kind: { type: "part", slot: "tusks" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.tusks", params: { broken: 0, scale: 0.75 } },
    materialZones: [],
    category: "face",
    printability: proto,
  },

  // ---- EYES -------------------------------------------------------------
  {
    id: "ganesha.eyes.serene",
    version: 2,
    name: "Serene Eyes",
    description: "Half-lidded, gently downcast — the meditative gaze.",
    kind: { type: "part", slot: "eyes" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: {
      kind: "procedural",
      generatorId: "ganesha.eyes",
      params: { lidCover: 1.32, gazeDown: 0.32, shapeX: 1, shapeY: 1, kohl: 0 },
    },
    materialZones: ["skinSecondary"],
    morphTargets: ["eyeSize", "eyeSpacing", "eyeHeight", "browHeight"],
    category: "face",
    printability: proto,
  },
  {
    id: "ganesha.eyes.open",
    version: 2,
    name: "Open Eyes",
    description: "Fully open, direct gaze.",
    kind: { type: "part", slot: "eyes" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: {
      kind: "procedural",
      generatorId: "ganesha.eyes",
      params: { lidCover: 0.95, gazeDown: 0.08, shapeX: 1, shapeY: 1.05, kohl: 0 },
    },
    materialZones: ["skinSecondary"],
    morphTargets: ["eyeSize", "eyeSpacing", "eyeHeight", "browHeight"],
    category: "face",
    printability: proto,
  },
  {
    id: "ganesha.eyes.lotus",
    version: 1,
    name: "Lotus Eyes",
    description: "Almond-shaped with kohl-lined outer corners.",
    kind: { type: "part", slot: "eyes" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: {
      kind: "procedural",
      generatorId: "ganesha.eyes",
      params: { lidCover: 1.15, gazeDown: 0.22, shapeX: 1.18, shapeY: 0.85, kohl: 1 },
    },
    materialZones: ["skinSecondary"],
    morphTargets: ["eyeSize", "eyeSpacing", "eyeHeight", "browHeight"],
    category: "face",
    printability: proto,
  },

  // ---- HANDS ------------------------------------------------------------
  {
    id: "ganesha.hands.classic",
    version: 1,
    name: "Classic Hands",
    description: "Sculpted hands; per-hand mudras set in the Hands panel.",
    kind: { type: "part", slot: "hands" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.hands" },
    materialZones: ["skin"],
    category: "hands",
    printability: proto,
  },

  // ---- CLOTHING ---------------------------------------------------------
  {
    id: "ganesha.garment.dhoti",
    version: 2,
    name: "Pleated Dhoti",
    description: "Full-length pleated dhoti with front fan.",
    kind: { type: "part", slot: "lowerGarment" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.dhoti", params: { length: 1, layered: 0 } },
    materialZones: ["garment", "garmentAccent"],
    category: "clothing",
    printability: proto,
  },
  {
    id: "ganesha.garment.dhotiShort",
    version: 2,
    name: "Short Dhoti",
    kind: { type: "part", slot: "lowerGarment" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.dhoti", params: { length: 0.5, layered: 0 } },
    materialZones: ["garment", "garmentAccent"],
    category: "clothing",
    printability: proto,
  },
  {
    id: "ganesha.garment.dhotiLayered",
    version: 1,
    name: "Layered Dhoti",
    description: "Dhoti with an accent over-layer.",
    kind: { type: "part", slot: "lowerGarment" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.dhoti", params: { length: 1, layered: 1 } },
    materialZones: ["garment", "garmentAccent"],
    category: "clothing",
    printability: proto,
  },
  {
    id: "ganesha.garment.shawl",
    version: 2,
    name: "Angavastram",
    description: "Shawl draped over both shoulders.",
    kind: { type: "part", slot: "upperGarment" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.shawl" },
    materialZones: ["garmentAccent"],
    category: "clothing",
    printability: proto,
  },

  // ---- CROWNS (attachments) --------------------------------------------
  {
    id: "ganesha.crown.kirita",
    version: 2,
    name: "Kirita Mukuta",
    description: "Tall tiered royal crown with front medallion.",
    kind: { type: "attachment", sockets: ["head.crown"] },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "crown.kirita" },
    materialZones: ["metal", "gem"],
    excludes: ["ganesha.crown.karanda", "ganesha.crown.fan"],
    category: "ornaments",
    printability: proto,
  },
  {
    id: "ganesha.crown.karanda",
    version: 2,
    name: "Karanda Mukuta",
    description: "Stacked-dome crown.",
    kind: { type: "attachment", sockets: ["head.crown"] },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "crown.karanda" },
    materialZones: ["metal", "gem"],
    excludes: ["ganesha.crown.kirita", "ganesha.crown.fan"],
    category: "ornaments",
    printability: proto,
  },
  {
    id: "ganesha.crown.fan",
    version: 1,
    name: "Prabha Crown",
    description: "Band crown with a radiating fan plate.",
    kind: { type: "attachment", sockets: ["head.crown"] },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "crown.fan" },
    materialZones: ["metal", "gem"],
    excludes: ["ganesha.crown.kirita", "ganesha.crown.karanda"],
    category: "ornaments",
    printability: proto,
  },

  // ---- NECKLACES / WAIST (attachments) ----------------------------------
  {
    id: "ganesha.necklace.haram",
    version: 2,
    name: "Haram Collar",
    description: "Gold collar with bead fringe and gem pendant.",
    kind: { type: "attachment", sockets: ["chest.necklace"] },
    deityCompatibility: ["any"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ornament.necklace" },
    materialZones: ["metal", "gem"],
    category: "ornaments",
    printability: proto,
  },
  {
    id: "ganesha.necklace.mala",
    version: 1,
    name: "Bead Mala",
    description: "Two strands of beads with gem accents.",
    kind: { type: "attachment", sockets: ["chest.necklace"] },
    deityCompatibility: ["any"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ornament.mala" },
    materialZones: ["metal", "gem"],
    category: "ornaments",
    printability: proto,
  },
  {
    id: "ganesha.waist.kamarband",
    version: 2,
    name: "Kamarband",
    description: "Waist band with hanging tassels.",
    kind: { type: "attachment", sockets: ["waist.ornament"] },
    deityCompatibility: ["any"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ornament.waistband" },
    materialZones: ["metal", "gem"],
    category: "ornaments",
    printability: proto,
  },

  // ---- JEWELLERY SETS (parts — follow their joints) ----------------------
  {
    id: "ganesha.earrings.kundala",
    version: 1,
    name: "Kundala Earrings",
    kind: { type: "part", slot: "earrings" },
    deityCompatibility: ["any"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ornament.earrings" },
    materialZones: ["metal", "gem"],
    category: "ornaments",
    printability: proto,
  },
  {
    id: "ganesha.armlets.vanki",
    version: 1,
    name: "Vanki Armlets",
    description: "Armbands on every rendered arm.",
    kind: { type: "part", slot: "armlets" },
    deityCompatibility: ["any"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ornament.armlets" },
    materialZones: ["metal", "gem"],
    category: "ornaments",
    printability: proto,
  },
  {
    id: "ganesha.bracelets.kada",
    version: 1,
    name: "Kada Bracelets",
    kind: { type: "part", slot: "bracelets" },
    deityCompatibility: ["any"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ornament.bracelets" },
    materialZones: ["metal"],
    category: "ornaments",
    printability: proto,
  },
  {
    id: "ganesha.anklets.payal",
    version: 1,
    name: "Payal Anklets",
    description: "Anklets with tiny bells.",
    kind: { type: "part", slot: "anklets" },
    deityCompatibility: ["any"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ornament.anklets" },
    materialZones: ["metal"],
    category: "ornaments",
    printability: proto,
  },

  // ---- HAND ITEMS / ATTRIBUTES (attachments) ----------------------------
  {
    id: "ganesha.item.modak",
    version: 2,
    name: "Modak",
    description: "The sweet of spiritual reward, held in a hand or trunk.",
    kind: {
      type: "attachment",
      sockets: [
        "arm.frontLeft.hand.item",
        "arm.frontRight.hand.item",
        "arm.backLeft.hand.item",
        "arm.backRight.hand.item",
        "trunk.tip",
      ],
    },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "item.modak" },
    materialZones: ["garmentAccent"],
    category: "attributes",
    printability: proto,
  },
  {
    id: "ganesha.item.lotus",
    version: 2,
    name: "Lotus",
    kind: {
      type: "attachment",
      sockets: [
        "arm.frontLeft.hand.item",
        "arm.frontRight.hand.item",
        "arm.backLeft.hand.item",
        "arm.backRight.hand.item",
      ],
    },
    deityCompatibility: ["any"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "item.lotus" },
    materialZones: ["gem", "garmentAccent"],
    category: "attributes",
    printability: proto,
  },
  {
    id: "ganesha.item.axe",
    version: 2,
    name: "Parashu",
    description: "The axe that severs attachment.",
    kind: {
      type: "attachment",
      sockets: [
        "arm.frontLeft.hand.item",
        "arm.frontRight.hand.item",
        "arm.backLeft.hand.item",
        "arm.backRight.hand.item",
      ],
    },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "item.axe" },
    materialZones: ["metal"],
    category: "attributes",
    printability: proto,
  },
  {
    id: "ganesha.item.noose",
    version: 2,
    name: "Pasha",
    description: "The noose that draws devotees near.",
    kind: {
      type: "attachment",
      sockets: [
        "arm.frontLeft.hand.item",
        "arm.frontRight.hand.item",
        "arm.backLeft.hand.item",
        "arm.backRight.hand.item",
      ],
    },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "item.noose" },
    materialZones: ["metal"],
    category: "attributes",
    printability: proto,
  },

  // ---- COMPANION (GLB-sourced) ------------------------------------------
  {
    id: "ganesha.companion.mushak",
    version: 1,
    name: "Mushak",
    description: "Ganesha's mouse companion at the base (GLB asset).",
    kind: { type: "attachment", sockets: ["base.platform"] },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "glb", path: "/assets/prototype/mushak.glb" },
    defaultTransform: { position: [0.24, 0, 0.2], rotation: [0, -0.6, 0] },
    materialZones: ["metal"],
    category: "companion",
    printability: proto,
  },
] as const;
