/**
 * Ganesha placeholder asset manifest.
 *
 * Every asset here is stage "prototype" with a procedural source — the
 * engine builds simple geometry so the whole pipeline (registry -> config ->
 * engine -> sockets -> materials) is exercised end to end. Replacing a
 * placeholder with a production sculpt means changing its `source` to a GLB
 * path and bumping `version`; nothing else in the app changes.
 */
import type { AssetDefinition } from "../types";

const proto = { printSourceAvailable: false } as const;

export const GANESHA_ASSETS: readonly AssetDefinition[] = [
  // ---- BODY -------------------------------------------------------------
  {
    id: "ganesha.body.classic",
    version: 1,
    name: "Classic Body",
    description: "Traditional rounded torso with the characteristic belly.",
    kind: { type: "part", slot: "body" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.body", params: { belly: 1 } },
    materialZones: ["skin"],
    category: "body",
    printability: proto,
  },
  {
    id: "ganesha.body.slender",
    version: 1,
    name: "Slender Body",
    description: "Slimmer, more upright torso build.",
    kind: { type: "part", slot: "body" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.body", params: { belly: 0.55 } },
    materialZones: ["skin"],
    category: "body",
    printability: proto,
  },

  // ---- HEAD -------------------------------------------------------------
  {
    id: "ganesha.head.classic",
    version: 1,
    name: "Classic Head",
    description: "Broad elephant head with a domed crown area.",
    kind: { type: "part", slot: "head" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.head", params: { dome: 1 } },
    materialZones: ["skin"],
    morphTargets: ["earSize", "cheekVolume"],
    category: "head",
    printability: proto,
  },
  {
    id: "ganesha.head.young",
    version: 1,
    name: "Bal Ganesha Head",
    description: "Rounder, youthful head shape.",
    kind: { type: "part", slot: "head" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.head", params: { dome: 0.8 } },
    materialZones: ["skin"],
    category: "head",
    printability: proto,
  },

  // ---- EARS -------------------------------------------------------------
  {
    id: "ganesha.ears.large",
    version: 1,
    name: "Large Ears",
    kind: { type: "part", slot: "ears" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.ears", params: { size: 1 } },
    materialZones: ["skin", "skinSecondary"],
    category: "head",
    printability: proto,
  },
  {
    id: "ganesha.ears.folded",
    version: 1,
    name: "Folded Ears",
    kind: { type: "part", slot: "ears" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.ears", params: { size: 0.7 } },
    materialZones: ["skin", "skinSecondary"],
    category: "head",
    printability: proto,
  },

  // ---- TRUNK ------------------------------------------------------------
  {
    id: "ganesha.trunk.leftCurl",
    version: 1,
    name: "Left-Curled Trunk",
    description: "Vamamukhi — trunk curving toward the left, the most common form.",
    kind: { type: "part", slot: "trunk" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.trunk", params: { curl: 1 } },
    materialZones: ["skin"],
    morphTargets: ["trunkLength", "trunkCurve"],
    category: "face",
    printability: proto,
  },
  {
    id: "ganesha.trunk.rightCurl",
    version: 1,
    name: "Right-Curled Trunk",
    description: "Dakshinabhimukhi — trunk curving toward the right.",
    kind: { type: "part", slot: "trunk" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.trunk", params: { curl: -1 } },
    materialZones: ["skin"],
    morphTargets: ["trunkLength", "trunkCurve"],
    category: "face",
    printability: proto,
  },

  // ---- TUSKS ------------------------------------------------------------
  {
    id: "ganesha.tusks.single",
    version: 1,
    name: "Ekadanta (Single Tusk)",
    description: "One whole tusk, one broken — the classic Ekadanta form.",
    kind: { type: "part", slot: "tusks" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.tusks", params: { broken: 1 } },
    materialZones: ["gem"],
    category: "face",
    printability: proto,
  },
  {
    id: "ganesha.tusks.double",
    version: 1,
    name: "Double Tusks",
    kind: { type: "part", slot: "tusks" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.tusks", params: { broken: 0 } },
    materialZones: ["gem"],
    category: "face",
    printability: proto,
  },

  // ---- EYES -------------------------------------------------------------
  {
    id: "ganesha.eyes.serene",
    version: 1,
    name: "Serene Eyes",
    kind: { type: "part", slot: "eyes" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.eyes", params: { openness: 0.6 } },
    materialZones: [],
    category: "face",
    printability: proto,
  },
  {
    id: "ganesha.eyes.open",
    version: 1,
    name: "Open Eyes",
    kind: { type: "part", slot: "eyes" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.eyes", params: { openness: 1 } },
    materialZones: [],
    category: "face",
    printability: proto,
  },

  // ---- CLOTHING ---------------------------------------------------------
  {
    id: "ganesha.garment.dhoti",
    version: 1,
    name: "Dhoti",
    description: "Traditional draped lower garment.",
    kind: { type: "part", slot: "lowerGarment" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.dhoti", params: { length: 1 } },
    materialZones: ["garment", "garmentAccent"],
    category: "clothing",
    printability: proto,
  },
  {
    id: "ganesha.garment.dhotiShort",
    version: 1,
    name: "Short Dhoti",
    kind: { type: "part", slot: "lowerGarment" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.dhoti", params: { length: 0.6 } },
    materialZones: ["garment", "garmentAccent"],
    category: "clothing",
    printability: proto,
  },
  {
    id: "ganesha.garment.shawl",
    version: 1,
    name: "Angavastram",
    description: "Upper shawl draped across the shoulder.",
    kind: { type: "part", slot: "upperGarment" },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ganesha.shawl" },
    materialZones: ["garmentAccent"],
    category: "clothing",
    printability: proto,
  },

  // ---- CROWNS (attachments) --------------------------------------------
  {
    id: "ganesha.crown.kirita",
    version: 1,
    name: "Kirita Mukuta",
    description: "Tall conical royal crown.",
    kind: { type: "attachment", sockets: ["head.crown"] },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "crown.kirita" },
    defaultTransform: { position: [0, 0.0, 0] },
    materialZones: ["metal", "gem"],
    excludes: ["ganesha.crown.karanda"],
    category: "ornaments",
    printability: proto,
  },
  {
    id: "ganesha.crown.karanda",
    version: 1,
    name: "Karanda Mukuta",
    description: "Tiered dome crown.",
    kind: { type: "attachment", sockets: ["head.crown"] },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "crown.karanda" },
    materialZones: ["metal", "gem"],
    excludes: ["ganesha.crown.kirita"],
    category: "ornaments",
    printability: proto,
  },

  // ---- ORNAMENTS (attachments) ------------------------------------------
  {
    id: "ganesha.necklace.haram",
    version: 1,
    name: "Haram Necklace",
    kind: { type: "attachment", sockets: ["chest.necklace"] },
    deityCompatibility: ["any"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ornament.necklace" },
    materialZones: ["metal", "gem"],
    category: "ornaments",
    printability: proto,
  },
  {
    id: "ganesha.waist.kamarband",
    version: 1,
    name: "Kamarband",
    kind: { type: "attachment", sockets: ["waist.ornament"] },
    deityCompatibility: ["any"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "ornament.waistband" },
    materialZones: ["metal"],
    category: "ornaments",
    printability: proto,
  },

  // ---- HAND ITEMS / ATTRIBUTES (attachments) ----------------------------
  {
    id: "ganesha.item.modak",
    version: 1,
    name: "Modak",
    description: "The sweet held in a hand — symbol of reward of sadhana.",
    kind: {
      type: "attachment",
      sockets: [
        "arm.frontLeft.hand.item",
        "arm.frontRight.hand.item",
        "arm.backLeft.hand.item",
        "arm.backRight.hand.item",
        "trunk.tip",
      ],
    },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "item.modak" },
    materialZones: ["garmentAccent"],
    category: "attributes",
    printability: proto,
  },
  {
    id: "ganesha.item.lotus",
    version: 1,
    name: "Lotus",
    kind: {
      type: "attachment",
      sockets: [
        "arm.frontLeft.hand.item",
        "arm.frontRight.hand.item",
        "arm.backLeft.hand.item",
        "arm.backRight.hand.item",
      ],
    },
    deityCompatibility: ["any"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "item.lotus" },
    materialZones: ["gem"],
    category: "attributes",
    printability: proto,
  },
  {
    id: "ganesha.item.axe",
    version: 1,
    name: "Parashu (Axe)",
    kind: {
      type: "attachment",
      sockets: [
        "arm.frontLeft.hand.item",
        "arm.frontRight.hand.item",
        "arm.backLeft.hand.item",
        "arm.backRight.hand.item",
      ],
    },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "item.axe" },
    materialZones: ["metal"],
    category: "attributes",
    printability: proto,
  },
  {
    id: "ganesha.item.noose",
    version: 1,
    name: "Pasha (Noose)",
    kind: {
      type: "attachment",
      sockets: [
        "arm.frontLeft.hand.item",
        "arm.frontRight.hand.item",
        "arm.backLeft.hand.item",
        "arm.backRight.hand.item",
      ],
    },
    deityCompatibility: ["ganesha"],
    stage: "prototype",
    source: { kind: "procedural", generatorId: "item.noose" },
    materialZones: ["metal"],
    category: "attributes",
    printability: proto,
  },
] as const;
