"""DevaForm Blender production template builder.

Builds the canonical DevaForm authoring scene from canonical-rig.json
(generated by `pnpm --filter @devaform/character-schema export-canonical`),
so the DCC rig can never drift from the schema:

- metric units, 1 unit = 1 m
- ARMATURE "devaform_rig" with one bone per canonical joint (bone names ==
  joint ids, head at the joint's rest position)
- SOCKET_<id> empties parented to their joints
- zone:* placeholder materials (flat colors; the app recolors zones live)
- a neutral camera + key light for look-dev

Usage (Blender 4.x):
    blender --python tools/blender/devaform_template.py
then save the result as devaform_template.blend for artists.
"""

import json
import os

import bpy
from mathutils import Vector

HERE = os.path.dirname(os.path.abspath(__file__))
RIG_JSON = os.path.join(HERE, "canonical-rig.json")

ZONE_COLORS = {
    "skin": (0.85, 0.60, 0.39, 1),
    "skinSecondary": (0.73, 0.47, 0.27, 1),
    "garment": (0.61, 0.11, 0.13, 1),
    "garmentAccent": (0.85, 0.61, 0.15, 1),
    "metal": (0.91, 0.68, 0.20, 1),
    "gem": (0.72, 0.12, 0.18, 1),
    "base": (0.49, 0.36, 0.23, 1),
}


def world_positions(skeleton):
    """Joint id -> rest world position (schema positions are parent-local)."""
    positions = {}
    by_id = {j["id"]: j for j in skeleton}
    def resolve(joint_id):
        if joint_id in positions:
            return positions[joint_id]
        joint = by_id[joint_id]
        local = Vector(joint["position"])
        world = local if joint["parent"] is None else resolve(joint["parent"]) + local
        positions[joint_id] = world
        return world
    for joint in skeleton:
        resolve(joint["id"])
    return positions


def build():
    with open(RIG_JSON, "r", encoding="utf-8") as fh:
        rig = json.load(fh)

    scene = bpy.context.scene
    scene.unit_settings.system = "METRIC"
    scene.unit_settings.scale_length = 1.0

    # Fresh collections
    for name in ("DevaForm_Rig", "DevaForm_Asset", "DevaForm_LookDev"):
        if name not in bpy.data.collections:
            collection = bpy.data.collections.new(name)
            scene.collection.children.link(collection)

    rig_collection = bpy.data.collections["DevaForm_Rig"]

    # Armature ------------------------------------------------------------
    armature_data = bpy.data.armatures.new("devaform_rig")
    armature = bpy.data.objects.new("devaform_rig", armature_data)
    rig_collection.objects.link(armature)
    bpy.context.view_layer.objects.active = armature
    bpy.ops.object.mode_set(mode="EDIT")

    positions = world_positions(rig["skeleton"])
    edit_bones = {}
    children = {}
    for joint in rig["skeleton"]:
        children.setdefault(joint["parent"], []).append(joint["id"])
    for joint in rig["skeleton"]:
        bone = armature_data.edit_bones.new(joint["id"])
        head = positions[joint["id"]]
        kids = children.get(joint["id"], [])
        # Tail toward the first child, or a 2 cm stub
        tail = positions[kids[0]] if kids else head + Vector((0, 0.02, 0))
        if (tail - head).length < 1e-4:
            tail = head + Vector((0, 0.02, 0))
        bone.head, bone.tail = head, tail
        edit_bones[joint["id"]] = bone
    for joint in rig["skeleton"]:
        if joint["parent"]:
            edit_bones[joint["id"]].parent = edit_bones[joint["parent"]]
    bpy.ops.object.mode_set(mode="OBJECT")

    # Socket empties -------------------------------------------------------
    for socket in rig["sockets"]:
        empty = bpy.data.objects.new(f"SOCKET_{socket['id']}", None)
        empty.empty_display_type = "ARROWS"
        empty.empty_display_size = 0.02
        joint_world = positions[socket["joint"]]
        empty.location = joint_world + Vector(socket["position"])
        empty.rotation_euler = socket["rotation"]
        empty.parent = armature
        empty.parent_type = "BONE"
        empty.parent_bone = socket["joint"]
        rig_collection.objects.link(empty)

    # Zone materials -------------------------------------------------------
    for zone in rig["materialZones"]:
        name = f"zone:{zone}"
        if name not in bpy.data.materials:
            material = bpy.data.materials.new(name)
            material.use_nodes = True
            bsdf = material.node_tree.nodes.get("Principled BSDF")
            if bsdf:
                bsdf.inputs["Base Color"].default_value = ZONE_COLORS.get(zone, (0.6, 0.6, 0.6, 1))

    # Look-dev camera + light ---------------------------------------------
    lookdev = bpy.data.collections["DevaForm_LookDev"]
    cam_data = bpy.data.cameras.new("devaform_cam")
    cam = bpy.data.objects.new("devaform_cam", cam_data)
    cam.location = (1.4, -1.7, 1.0)
    cam.rotation_euler = (1.18, 0, 0.69)
    lookdev.objects.link(cam)
    scene.camera = cam
    light_data = bpy.data.lights.new("devaform_key", type="AREA")
    light_data.energy = 400
    light = bpy.data.objects.new("devaform_key", light_data)
    light.location = (1.5, -1.2, 2.2)
    light.rotation_euler = (0.9, 0.2, 0.6)
    lookdev.objects.link(light)

    print(f"DevaForm template ready: {len(rig['skeleton'])} bones, {len(rig['sockets'])} sockets")


if __name__ == "__main__":
    build()
